# Generated by Django 4.0 on 2023-01-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0007_productratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productratings',
            old_name='Customer',
            new_name='customer',
        ),
    ]
