# Generated by Django 4.0 on 2023-01-15 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Food_id', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=200)),
                ('FoodPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('Table_id', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNum', models.IntegerField()),
                ('Payment', models.CharField(choices=[('Not_Paid', 'Not_Paid'), ('UPI', 'UPI'), ('CASH', 'CASH')], default='Not_Paid', max_length=20)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Table', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tables')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('OrderDetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('FoodItem', models.ManyToManyField(to='ecommerce.Food')),
                ('OrderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Foods', models.ManyToManyField(to='ecommerce.Food')),
            ],
        ),
    ]
